### ISSUE TITLE
ModuleNotFoundError: No module named '_client'

### ISSUE THREAD

**Issue by DaHepfe** [eugenetriguba/lirc#2]
Hey sorry if this a stupid question, i´m realy new into python and ""programming"" stuff. 
I have LIRC installed and its working very well! I can send signals with: 
`irsend SEND_ONCE PHILIPS_MULTI_TV2 KEY_POWER`

Now i have installed your package and trying to run it. In my script file is this: 
`import lirc`

`client = lirc.Client()`

`print(client.version())`

I also tryed to send some signales but this isn´t working. All what i get back in the console is this:

`Traceback (most recent call last):
  File "ONTV.py", line 1, in <module>
    import lirc
  File "/usr/lib/python3/dist-packages/lirc/__init__.py", line 7, in <module>
    from .client import get_default_lircrc_path
  File "/usr/lib/python3/dist-packages/lirc/client.py", line 38, in <module>
    import _client
ModuleNotFoundError: No module named '_client'
`

I´m running it on a RaspberryPi 3B,  OS: "Raspbian GNU/Linux Version10 (buster) " , Kernel: 5.10.17-v7+, Python Version: 3.7.3
The IR Module im using is a GPIO Extensionboard: [https://www.amazon.de/gp/product/B07XMMSFHF/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1](url)

I installed LIRC exactly like in this tutorial: [https://devkimchi.com/2020/08/12/turning-raspberry-pi-into-remote-controller/](url)

I hope anyone can help me 😅 

Sorry for my bad english btw 
Greetings from Germany!

**Comment by DaHepfe** [comment]
Nervermind i tryed out something now its working 😅

**Comment by Siyou-Chen** [comment]
I also meet the problem now when using RaspberryPi 4B. How did you fix the problem？Hope you can help me.
Greetings from China!

**Comment by DaHepfe** [comment]
> I also meet the problem now when using RaspberryPi 4B. How did you fix the problem？Hope you can help me. Greetings from China!

Hey, do you also use the same Extensionboard? I have tryed out this: 

```
from lirc import Client, LircdConnection
import lirc

client = lirc.Client()
client.send_once("PHILIPS", "KEY_POWER")
```

It works fine in my case.

Here is my lirc_options.conf:


```
[lircd]
nodaemon        = False
driver          = default
device          = /dev/lirc0
output          = /var/run/lirc/lircd
pidfile         = /var/run/lirc/lircd.pid
#plugindir       = /usr/lib/lirc/plugins
permission      = 666
allow-simulate  = No
repeat-max      = 600
#effective-user =
#listen         = [address:]port
#connect        = host[:port]
#loglevel       = 6
#release        = true
#release_suffix = _EVUP
#logfile        = ...
#driver-options = ...

[lircmd]
uinput          = False
nodaemon        = False

# [modinit]
# code = /usr/sbin/modprobe lirc_serial
# code1 = /usr/bin/setfacl -m g:lirc:rw /dev/uinput
# code2 = ...


# [lircd-uinput]
# add-release-events = False
# release-timeout    = 200
# release-suffix     = _EVUP
```

and my boot/config.txt

```
dtoverlay=gpio-ir,gpio_pin=18
dtoverlay=gpio-ir-tx,gpio_pin=17
```


Ouh and im using Python3 to run it. I hope i can help you :)

Greetings from Germany! :)
